In [454]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [455]:
phone= pd.read_csv('phone.csv')
phone

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,...,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,...,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
4,4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,...,12.0,32.0,Android,Yes,Yes,Yes,1,No,No,49990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,1354,Intex Aqua A2,Intex,Aqua A2,1500,4.00,Yes,480,800,4,...,5.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,2599
1355,1355,Videocon Infinium Z51 Nova+,Videocon,Infinium Z51 Nova+,2000,5.00,Yes,480,854,4,...,8.0,5.0,Android,Yes,Yes,Yes,2,Yes,No,2940
1356,1356,Intex Aqua Y4,Intex,Aqua Y4,1700,4.50,Yes,480,854,2,...,5.0,2.0,Android,Yes,Yes,No,2,Yes,No,2999
1357,1357,iBall Andi4 B20,iBall,Andi4 B20,1250,4.00,Yes,480,800,1,...,2.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,2498
1358,1358,iBall Andi Avonte 5,iBall,Andi Avonte 5,2150,5.00,Yes,480,854,4,...,8.0,0.0,Android,Yes,Yes,Yes,2,Yes,No,3999

In [456]:
phone.isnull().sum()

Unnamed: 0                0
Name                      0
Brand                     0
Model                     0
Battery capacity (mAh)    0
Screen size (inches)      0
Touchscreen               0
Resolution x              0
Resolution y              0
Processor                 0
RAM (MB)                  0
Internal storage (GB)     0
Rear camera               0
Front camera              0
Operating system          0
Wi-Fi                     0
Bluetooth                 0
GPS                       0
Number of SIMs            0
3G                        0
4G/ LTE                   0
Price                     0
dtype: int64

In [457]:
phone['Price(£)']=phone['Price']/93.55
phone.rename(columns = {'Price':'Price(INR)'}, inplace = True)
phone

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price(INR),Price(£)
0,0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,...,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998,630.657402
1,1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,...,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999,299.294495
2,2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,...,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900,1142.704436
3,3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,...,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900,672.367718
4,4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,...,32.0,Android,Yes,Yes,Yes,1,No,No,49990,534.366649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,1354,Intex Aqua A2,Intex,Aqua A2,1500,4.00,Yes,480,800,4,...,0.3,Android,Yes,Yes,Yes,2,Yes,No,2599,27.781935
1355,1355,Videocon Infinium Z51 Nova+,Videocon,Infinium Z51 Nova+,2000,5.00,Yes,480,854,4,...,5.0,Android,Yes,Yes,Yes,2,Yes,No,2940,31.427044
1356,1356,Intex Aqua Y4,Intex,Aqua Y4,1700,4.50,Yes,480,854,2,...,2.0,Android,Yes,Yes,No,2,Yes,No,2999,32.057723
1357,1357,iBall Andi4 B20,iBall,Andi4 B20,1250,4.00,Yes,480,800,1,...,0.3,Android,Yes,Yes,Yes,2,Yes,No,2498,26.702298
1358,1358,iBall Andi Avonte 5,iBall,Andi Avonte 5,2150,5.00,Yes,480,854,4,...,0.0,Android,Yes,Yes,Yes,2,Yes,No,3999,42.747194

In [458]:
map={'Yes':1,'No':0}
list=['Touchscreen','Wi-Fi','Bluetooth','GPS','3G','4G/ LTE']
for i in list:
    phone[i]=phone[i].map(map)
phone

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price(INR),Price(£)
0,0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,1,1440,3120,8,...,16.0,Android,1,1,1,2,1,1,58998,630.657402
1,1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,1,1080,2400,8,...,16.0,Android,1,1,1,2,1,1,27999,299.294495
2,2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,1,1242,2688,6,...,12.0,iOS,1,1,1,2,1,1,106900,1142.704436
3,3,iPhone 11,Apple,iPhone 11,3110,6.10,1,828,1792,6,...,12.0,iOS,1,1,1,2,1,1,62900,672.367718
4,4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,1,1080,2340,8,...,32.0,Android,1,1,1,1,0,0,49990,534.366649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,1354,Intex Aqua A2,Intex,Aqua A2,1500,4.00,1,480,800,4,...,0.3,Android,1,1,1,2,1,0,2599,27.781935
1355,1355,Videocon Infinium Z51 Nova+,Videocon,Infinium Z51 Nova+,2000,5.00,1,480,854,4,...,5.0,Android,1,1,1,2,1,0,2940,31.427044
1356,1356,Intex Aqua Y4,Intex,Aqua Y4,1700,4.50,1,480,854,2,...,2.0,Android,1,1,0,2,1,0,2999,32.057723
1357,1357,iBall Andi4 B20,iBall,Andi4 B20,1250,4.00,1,480,800,1,...,0.3,Android,1,1,1,2,1,0,2498,26.702298
1358,1358,iBall Andi Avonte 5,iBall,Andi Avonte 5,2150,5.00,1,480,854,4,...,0.0,Android,1,1,1,2,1,0,3999,42.747194

In [459]:
phone['Operating system'].nunique()

7

In [460]:
p = pd.get_dummies(phone,columns=['Operating system','Brand','Model'])
p

,Unnamed: 0,Name,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,RAM (MB),Internal storage (GB),...,Model_reka,Model_reka 2,Model_reka Black,Model_reka Note,Model_reka Plus,Model_reka S,Model_srt.phone,Model_t.phone,Model_t.phone P,Model_topia
0,0,OnePlus 7T Pro McLaren Edition,4085,6.67,1,1440,3120,8,12000,256.000,...,0,0,0,0,0,0,0,0,0,0
1,1,Realme X2 Pro,4000,6.50,1,1080,2400,8,6000,64.000,...,0,0,0,0,0,0,0,0,0,0
2,2,iPhone 11 Pro Max,3969,6.50,1,1242,2688,6,4000,64.000,...,0,0,0,0,0,0,0,0,0,0
3,3,iPhone 11,3110,6.10,1,828,1792,6,4000,64.000,...,0,0,0,0,0,0,0,0,0,0
4,4,LG G8X ThinQ,4000,6.40,1,1080,2340,8,6000,128.000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,1354,Intex Aqua A2,1500,4.00,1,480,800,4,512,8.000,...,0,0,0,0,0,0,0,0,0,0
1355,1355,Videocon Infinium Z51 Nova+,2000,5.00,1,480,854,4,1000,8.000,...,0,0,0,0,0,0,0,0,0,0
1356,1356,Intex Aqua Y4,1700,4.50,1,480,854,2,512,4.000,...,0,0,0,0,0,0,0,0,0,0
1357,1357,iBall Andi4 B20,1250,4.00,1,480,800,1,256,0.512,...,0,0,0,0,0,0,0,0,0,0
1358,1358,iBall Andi Avonte 5,2150,5.00,1,480,854,4,1000,8.000,...,0,0,0,0,0,0,0,0,0,0

In [461]:
p1=p.drop(['Name','Unnamed: 0','Price(INR)'],axis=1)

In [462]:
x = p1.drop('Price(£)',axis=1)
y = p1['Price(£)']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=0)
reg = LinearRegression()

In [463]:
reg.fit(X_train,y_train)
reg.score(X_train,y_train)

1.0

In [464]:
reg.score(X_test,y_test)

0.6018553868851988

In [465]:
from sklearn.linear_model import Ridge
ridge=Ridge(1)
ridge.fit(X_train,y_train)
ridge.score(X_train,y_train)

0.9122664960132005

In [466]:
ridge.score(X_test,y_test)

0.7015706320745213